CREATE TABLE VENDOR_QUALIFICATION_MASTER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VQF_REF_NO VARCHAR2(4000),
    MATERIAL_ITEM VARCHAR2(4000),
    DISPOSITION VARCHAR2(4000),
    SUPPLIER1_INFO VARCHAR2(4000),
    SUPPLIER2_INFO VARCHAR2(4000),
    SUPPLIER3_INFO VARCHAR2(4000),
    REMARK CLOB,
    CHECKED_BY VARCHAR2(50),
    CHECKED_DATE DATE,
    CREATED_BY VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    STATUS CHAR(1) DEFAULT '1'
);

CREATE TABLE VENDOR_QUALIFICATION_CRITERIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MASTER_ID NUMBER NOT NULL,
    CRITERIA VARCHAR2(255),
    RATING NUMBER(5,2),
    SUPPLIER1 VARCHAR2(255),
    SUPPLIER2 VARCHAR2(255),
    SUPPLIER3 VARCHAR2(255),
    CREATED_BY VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    STATUS CHAR(1) DEFAULT '1',
    CONSTRAINT FK_MASTER_ID FOREIGN KEY (MASTER_ID)
        REFERENCES VENDOR_QUALIFICATION_MASTER(ID)
        ON DELETE CASCADE
);


-- ── Preventive Maintenance Tables ────────────────────────────────────────────

CREATE TABLE PRODUCTION.PREVENTIVE_MAINTENANCE_MASTER (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSPECTION_MONTH VARCHAR2(7),
    LINE             VARCHAR2(100),
    MODEL            VARCHAR2(100),
    PLANT            VARCHAR2(20),
    WEEK1_DATE       DATE,
    WEEK1_TIME       TIMESTAMP,
    WEEK2_DATE       DATE,
    WEEK2_TIME       TIMESTAMP,
    WEEK3_DATE       DATE,
    WEEK3_TIME       TIMESTAMP,
    WEEK4_DATE       DATE,
    WEEK4_TIME       TIMESTAMP,
    WEEK5_DATE       DATE,
    WEEK5_TIME       TIMESTAMP,
    REMARKS          CLOB,
    PM_STATUS        VARCHAR2(50)  DEFAULT 'Pending Verification',
    REJECTION_REASON VARCHAR2(4000),
    VERIFIED_BY      VARCHAR2(50),
    CREATED_BY       VARCHAR2(50),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE
);

-- ── If the table already exists, just add the missing column ─────────────────
-- Run this ALTER if you already have the table in your database:
ALTER TABLE PRODUCTION.PREVENTIVE_MAINTENANCE_MASTER
    ADD REJECTION_REASON VARCHAR2(4000);

